spring:
  profiles:
    active: local
  jackson:
    time-zone: Asia/Seoul
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - talk_message
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id

kakao:
  linked-url: ${KAKAO_LINKED_URL}
  message-send-uri: /v2/api/talk/memo/default/send
  notification-title : ${KAKAO_NOTIFICATION_TITLE}

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

server:
  forward-headers-strategy: native
  cors: ${CORS_ALLOWED}
