spring:
  profiles:
    active: local
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
