name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build Job (Dev)"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            CURRENT_TZ=$(timedatectl | grep "Time zone" | awk '{print $3}')
            if [ "$CURRENT_TZ" != "Asia/Seoul" ]; then
              sudo timedatectl set-timezone Asia/Seoul
            fi
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker stop bookmark-app || true
            docker rm -f bookmark-app || true
            docker run -d -p 8080:8080 --env-file ~/app/.env --name bookmark-app ${{ secrets.DOCKER_IMAGE_NAME }}
